[book]
authors = ["Elliot Maître", "Yann Labbé"]
language = "en"
multilingual = false
src = "docs/book"
title = "HappyPose"

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/agimus-project/happypose"
