name: happypose
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
  - nvidia::cudatoolkit==11.3.1
  - python=3.9
  - pip
  - pytorch::pytorch==1.11.0
  - torchvision==0.12.0
  - geckodriver
  - firefox
  - opencv
  - pinocchio
