name: happypose
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
  - nvidia::cudatoolkit==12.1
  - python=3.9
  - pip
  - pytorch::pytorch==2.1
  - torchvision==0.16
  - geckodriver
  - firefox
  - opencv
  - pinocchio
