name: happypose_torch2
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
  - pytorch-cuda==12.1
  - python=3.9
  - pip
  - pytorch==2.1
  - torchvision==0.16
  - mkl==2024.0.0
  - geckodriver
  - firefox
  - opencv
  - pinocchio
  - torchtnt
  - torchnet
