[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.coverage.run]
omit = ["cosypose", "megapose6d"]

[tool.isort]
profile = "black"

[tool.mypy]
exclude = ["cosypose", "megapose6d"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "pybullet"

[tool.poetry]
authors = ["Elliot Maître", "Yann Labbé"]
description = "Toolbox and trackers for object pose-estimation"
license = "BSD-2-Clause"
name = "happypose"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
panda3d = {optional = true, version = "=1.10.13"}
pin = "^2.6.20"
pybullet = {optional = true, version = "^3.2.5"}
python = ">=3.9,<3.11"
torch = [
  {source = "torch_cpu", version = "1.11.0+cpu"},
  #{markers = "extra!='cuda'", source = "torch_cpu", version = "1.11.0+cpu"},
  #{markers = "extra=='cuda'", source = "torch_cu113", version = "1.11.0+cu113"}
]
torchvision = [
  {source = "torch_cpu", version = "0.12.0+cpu"},
  #{markers = "extra!='cuda'", source = "torch_cpu", version = "0.12.0+cpu"},
  #{markers = "extra=='cuda'", source = "torch_cu113", version = "0.12.0+cu113"}
]

[tool.poetry.extras]
cuda = []
render = ["panda3d", "pybullet"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
coverage = {extras = ["toml"], version = "^7.2.5"}
ipython = "^8.12.2"
pre-commit = "^3.2.1"
pybind11 = "^2.10.4"
ruff = "^0.0.290"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = "^2.0.0"
sphinx = "^6.2.1"

[[tool.poetry.source]]
name = "torch_cpu"
priority = "supplemental"
url = "https://download.pytorch.org/whl/cpu"

[[tool.poetry.source]]
name = "torch_cu113"
priority = "supplemental"
url = "https://download.pytorch.org/whl/cu113"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.urls]
changelog = "https://github.com/agimus-project/happypose/blob/main/CHANGELOG.md"

[tool.ruff]
extend-exclude = ["cosypose", "megapose6d"]
extend-ignore = ["D203", "D213"]
extend-select = ["A", "B", "C", "COM", "D", "EM", "EXE", "G", "N", "PTH", "RET", "RUF", "UP", "W", "YTT"]
target-version = "py39"

[tool.tomlsort]
all = true
