name: Tests with poetry

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install EGL mesa - required for Panda3D renderer
        run: sudo apt-get update && sudo apt-get install -qqy libegl1-mesa libegl1-mesa-dev rclone

      - name: Setup poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install happypose
        run: poetry install --with dev -E render -E cpu

      - name: Download pre-trained models required for tests
        run: |
          mkdir local_data
          poetry run python -m happypose.toolbox.utils.download \
                               --cosypose_model=detector-bop-ycbv-pbr--970850 \
                               --cosypose_model=coarse-bop-ycbv-pbr--724183 \
                               --cosypose_model=refiner-bop-ycbv-pbr--604090 \
                               --megapose_models

          cd tests/data
          git clone https://github.com/petrikvladimir/happypose_test_data.git crackers_example

      - name: Run tests
        run: |
          poetry run python -m unittest
