name: Tests & Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Install EGL mesa - required for Panda3D renderer
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libegl1-mesa libegl1-mesa-dev
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: happypose
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Install happypose
        run: |
          cd happypose/pose_estimators/cosypose
          python setup.py install
          cd ../../..
          pip install -e .
          
      - name: Install bop toolkit (temporal fix)
        run: |
          mkdir libs
          cd libs
          git clone https://github.com/ylabbe/bop_toolkit/ -b dataset-tools
          cd bop_toolkit
          sed 's/==.*$//' requirements.txt > req_nover.txt
          pip install -r req_nover.txt -e .

      - name: Run tests
        run: | 
          pip install pytest coverage
          coverage run -m pytest tests
      - uses: codecov/codecov-action@v3
